### PR TITLE
Trying to dry up some code

### PR DESCRIPTION
**Pull request by jsalyer23**
Title: Calling Instance Methods From Within Class Methods

Body:

I want to be able to use an `instance` method that returns a `String` containing all the text needed to call/set the data to a `new instance` of my `PokedexSearch` Class. I am using the data from the Associative `Array` returned from the database.

I have read that the only way I can call an `instance` method from within a `class` method is to create a `new instance` within the `class` method then call the`instance` method I want to use on the `new instance`. When I try to use this approach, all of my `attr_reader` methods return `nil`. When I look at what's returned from `pokemon_traits`(my instance method i'd like to use) from within Minitest, everything looks like I expect it to that's being returned from`pokemon_traits`.

I've also tried to set the value of `pokemon_traits` to an instance variable from within the class but get the same result. In both cases i'm trying to just "plug" in my `pokemon_traits` method into the `new instance` returned from my class method.

Expected: A new instance of `PokedexSearch` is created, contains the correct data taken from the database request, and the data can be accessed after creation (ex. `PokedexSearch.search("Female")`
will create an `Array` of `objects` containing "Female" which can then be accessed using `instance`methods)

Actual: "traits[\"id\"], traits[\"pokedex_id\"], traits[\"name\"], traits[\"weight\"], traits[\"height\"], traits[\"gender\"], traits[\"favorite\"], traits[\"hp\"], traits[\"cp\"], traits[\"date_added\"], traits[\"evolves\"], traits[\"type1\"], traits[\"type2\"]"

[here's a link.](https://github.com/jsalyer23/oop_pokedex/blob/19ffd63155ea8cf6dcc42046cb1c140362cba6e8/app/models/search.rb)

I thought it might have something to do with it being a `String` instead of just the actual text but am having trouble finding a way around that. It just seems like a lot to type out for three different methods where I get the same data out of the database request. What am I doing wrong?

### CODE REVIEW

**Comment by sumeetjain** [comment]
First, thanks for the good explanation of what's going on. I have most of the information I need to help. I need to know which specific class method you're calling and where in that class method you're calling an instance method (Give me line numbers).

**Comment by jsalyer23** [comment]
I must have deleted it from where I was calling it within the `find_by_name` class method on line 60. `pokemon_traits` is on line 30. Basically I just took out everything I was passing into the new object that was being returned and replaced it with `pokemon_traits`, `self.pokemon_traits`,`@traits`, and also tried calling `pokemon_traits`on a new instance I created at the beginning of the `find_by_name` method. Sorry for the confusion.

**Comment by sumeetjain** [comment]
To make sure I understand...

Are you trying to make the code that is currently this:

``` ruby
PokedexSearch.new(traits["id"], traits["pokedex_id"], traits["name"], traits["weight"], traits["height"], traits["gender"], traits["favorite"], traits["hp"], traits["cp"], traits["date_added"], traits["evolves"], traits["type1"], traits["type2"])
```

Into something like this:

``` ruby
PokedexSearch.new(some_method)
```

Yes?

If so, I suggest abandoning that pursuit.

It's fine to use a variable to contain a single value that'll be passed into a function, e.g.:

``` ruby
x = "Sumeet"
Person.new(x)
```

But it's pretty much impossible to define a comma-separated list of arguments as a variable to then pass around.

I can see why you'd think that the instance method you've defined is helping make your code more readable and might help DRY things up. But in this case, the appropriate solution would be what you have now: Referencing the argument values explicitly.

**Comment by jsalyer23** [comment]
Ok thank you!

**Pull request closed without merging**
